version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao-contas-pagar-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:16.2
    container_name: gestao-contas-pagar-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestao_contas_pagar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
